[package]
name = "xor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
bytes = "1.3.0"
clap = { version = "4.0.27", features = ["derive"] }
hex = "0.4.3"
thiserror = "1.0.37"
